front_webapp/admin/app/__init__.py
from flask import Flask, render_template, jsonify

app = Flask(__name__)

from werkzeug.contrib.cache import SimpleCache

app.config.from_object('config')
cache = SimpleCache(default_timeout=app.config['CACHE_TIMEOUT'])


# Sample HTTP error handling
@app.errorhandler(404)
def not_found(error):
    '''Error handling'''
    return render_template('404.html'), 404

@app.route('/help', methods = ['GET'])
def help():
    """Print available functions."""
    if app.debug:
        print(app.view_functions.keys())
        func_list = {}
        for rule in app.url_map.iter_rules():
            if rule.endpoint != 'static':
                func_list[rule.rule] = app.view_functions[rule.endpoint].__doc__
        return jsonify(func_list)
    else:
        return render_template('404.html'), 404

# Import a module / component using its blueprint handler variable
from app.mod_auth.controllers import mod_auth as auth_module

# Register blueprint(s)
app.register_blueprint(auth_module)

from app import views

front_webapp/admin/app/mod_auth/controllers.py
from functools import wraps
from flask import (
        redirect, url_for, session, 
        request, flash, Blueprint
)
from flask_oauthlib.client import OAuth
from app import app

oauth = OAuth(app)

google = oauth.remote_app(
    'google',
    consumer_key=app.config.get('GOOGLE_ID'),
    consumer_secret=app.config.get('GOOGLE_SECRET'),
    request_token_params={
        'scope': 'https://www.googleapis.com/auth/userinfo.email'
    },
    base_url='https://www.googleapis.com/oauth2/v1/',
    request_token_url=None,
    access_token_method='POST',
    access_token_url='https://accounts.google.com/o/oauth2/token',
    authorize_url='https://accounts.google.com/o/oauth2/auth',
)

# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_auth = Blueprint('auth', __name__, url_prefix='/auth')

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'google_token' not in session or not\
        google.get('userinfo').data['email'].endswith('@namely.com'):
            flash('Please log in')
            return redirect(url_for('index'))
        return f(*args, **kwargs)
    return decorated_function

@mod_auth.route('/login', methods=['GET', 'POST'])
def login():
    '''Starts login'''
    session.clear()
    return google.authorize(callback=url_for('auth.authorized', _external=True))

@mod_auth.route('/logout')
def logout():
    '''Logs out the user'''
    session.pop('google_token', None)
    session.clear()
    return redirect(url_for('index'))

@mod_auth.route('/login/authorized')
@google.authorized_handler
def authorized(resp):
    '''checks if user is an authorized user'''
    if resp is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )
    session['google_token'] = (resp['access_token'], '')
    print('USER AUTH: %s' % google.get('userinfo').data.get('email'))
    return redirect(url_for('upload.upload_file'))

@google.tokengetter
def get_google_oauth_token():
    return session.get('google_token')

front_webapp/admin/app/views.py
#!/usr/bin/python
# -*- encoding: utf-8 -*-
'''Views'''

from flask import render_template

from app import app


CACHE_TIMEOUT = app.config['CACHE_TIMEOUT']

@app.route('/')
def index():
    '''index page, redirects to login page'''
    return render_template('auth/login.html')

front_webapp/admin/app/templates/2fa.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <h1>Two Factor Authentication Setup</h1>
    <p>You are almost done! Please start FreeOTP on your smartphone and scan the following QR Code with it:</p>
    <p><img id="qrcode" src="{{ url_for('qrcode') }}"></p>
    <p>I'm done, take me to the <a href="{{ url_for('login') }}">Login</a> page!</p>
{% endblock %}

front_webapp/admin/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Two Factor Authentication Demo{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('index') }}">Two Factor Auth Demo</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

front_webapp/admin/app/templates/blocks/field_dropdown.html
<li style="list-style-type: none; border-bottom:1px dotted #CCC; margin-top:20px;">
  <label style="height:40px; width:150px; text-align:top;">{{column_name}} :</label>
  <select name="{{column_name}}" width="100px" style ="float:right;">
    <option >{{alias_field_dict[column_name]}}</option>
    {% for column in field_list %}  
    <option >{{column}}</option>
    {% endfor %}
  </select>
</li>

front_webapp/admin/app/templates/blocks/layout.html
<!DOCTYPE html>
<html>
<head>
<title>Clean a file for import</title>
<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
<link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
</head>
<body>
<header>
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <img class="navbar-brand" src="{{url_for('static',filename='img/icon.png')}}" width=70px	>
            {% if 'google_token' not in session %}
            <a class="navbar-brand" href="{{ url_for('auth.login') }}">log in</a>
            {% else %}
            <a class="navbar-brand" href="{{url_for('upload.upload_file')}}">Import a file</a>
            <a class="navbar-brand" href="{{ url_for('auth.logout') }}">log out</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="text-primary text-center">
    {% for message in get_flashed_messages() %}
    <strong>{{ message }}</strong>
    {% endfor %}
</div>
</p>
      </header>
        <div class= "container">
{% block content %}
{% endblock %}
                         </div>
                </body>
</html>

front_webapp/admin/app/templates/blocks/multiple_downloads.html
<!-- extend the base layout -->
{% extends "blocks/layout.html" %}

{% block content %}

<form action="" method="post" class="new-entry" )>

  {% for file in files %}

    <button  type="submit" name = "{{file}}" value ="ok" class="btn btn-primary">{{file}}</button>
    <br>

  {% endfor %}
    <br>
    <button  type="submit" name = "next" value="ok" class="btn btn-primary">Next</button>
    </button>
</form>
 
 {% endblock %}

front_webapp/admin/app/templates/blocks/row.html
    <tr valign="top">
      {% for element in row %}
        <td  >{{element}}</td>
        {% endfor %}  
    </tr>

front_webapp/admin/app/templates/blocks/select_column.html
<!-- extend the base layout -->
{% extends "blocks/layout.html" %}

{% block content %}

<form action="" method="post" class="new-entry">
    <div >
        <ul style="width:500px;">

                <select name="selected_column" width="100px" style ="float:right;">
                    {% for column in columns %}  
                    <option >{{column}}</option>
                    {% endfor %}
                </select>
        </div>
        <br>
        <button  type="submit" class="btn btn-primary">Next</button>
    </form>

    {% endblock %}

front_webapp/admin/app/templates/blocks/upload_file.html
{% extends "blocks/layout.html" %}
{%block content %}
    <title>Upload new File</title>
    <h1>Upload new File</h1>
    <form action="" method=post enctype=multipart/form-data>
      <p><input type=file name=file>
         <input type=submit value=Upload>
    </form>
{% endblock %}

front_webapp/admin/app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
    {% if current_user.is_authenticated() %}
    <h1>Welcome, {{ current_user.username }}!</h1>
    {% else %}
    <h1>Welcome, Stranger!</h1>
    <p>Please <a href="{{ url_for('register') }}">Register</a> or <a href="{{ url_for('login') }}">Login</a>.</p>
    {% endif %}
{% endblock %}

front_webapp/admin/app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <h1>Login</h1>
    {{ wtf.quick_form(form) }}
{% endblock %}

front_webapp/admin/app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <h1>Register</h1>
    <p>Before you submit this form, please ensure you have <a href="https://fedorahosted.org/freeotp/">FreeOTP</a> installed on your smartphone, as you will need it to complete your registration. Download from <a href="https://itunes.apple.com/us/app/freeotp/id872559395">iTunes</a> | <a href="https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp">Google Play</a></p>
    {{ wtf.quick_form(form) }}
    <br>
    <div class="alert alert-danger" role="alert">Note: The next page will show sensitive information. Make sure nobody can see your screen before pressing the Register button.</div>
{% endblock %}